-- keybindings
local SI = Teleporter.SI

ZO_CreateStringId("SI_BINDING_NAME_BMU_TOGGLE_MAIN", SI.get(SI.TELE_KEYBINDING_TOGGLE_MAIN))
ZO_CreateStringId("SI_BINDING_NAME_BMU_TOGGLE_MAIN_ACTIVE_QUESTS", SI.get(SI.TELE_KEYBINDING_TOGGLE_MAIN_ACTIVE_QUESTS))
ZO_CreateStringId("SI_BINDING_NAME_BMU_TOGGLE_MAIN_RELATED_ITEMS", SI.get(SI.TELE_KEYBINDING_TOGGLE_MAIN_RELATED_ITEMS))
ZO_CreateStringId("SI_BINDING_NAME_BMU_TOGGLE_MAIN_CURRENT_ZONE", SI.get(SI.TELE_KEYBINDING_TOGGLE_MAIN_CURRENT_ZONE))
ZO_CreateStringId("SI_BINDING_NAME_BMU_TOGGLE_MAIN_DELVES", SI.get(SI.TELE_KEYBINDING_TOGGLE_MAIN_DELVES))
ZO_CreateStringId("SI_BINDING_NAME_BMU_WAYSHRINE_UNLOCK", SI.get(SI.TELE_KEYBINDING_WAYSHRINE_UNLOCK))
ZO_CreateStringId("SI_BINDING_NAME_BMU_REFRESH", SI.get(SI.TELE_KEYBINDING_REFRESH))
for i=1, 5, 1 do
    ZO_CreateStringId("SI_BINDING_NAME_BMU_FAVORITE_ZONE_" .. tostring(i), SI.get(SI.TELE_UI_FAVORITE_ZONE) .. " " .. tostring(i))
    ZO_CreateStringId("SI_BINDING_NAME_BMU_FAVORITE_PLAYER_" .. tostring(i), SI.get(SI.TELE_UI_FAVORITE_PLAYER) .. " " .. tostring(i))
end
ZO_CreateStringId("SI_BINDING_NAME_BMU_GROUP_LEADER", SI.get(SI.TELE_KEYBINDING_GROUP_LEADER))
ZO_CreateStringId("SI_BINDING_NAME_BMU_CURRENT_ZONE", SI.get(SI.TELE_KEYBINDING_CURRENT_ZONE))
ZO_CreateStringId("SI_BINDING_NAME_BMU_PRIMARY_RESIDENCE", SI.get(SI.TELE_KEYBINDING_PRIMARY_RESIDENCE))
ZO_CreateStringId("SI_BINDING_NAME_BMU_PRIMARY_RESIDENCE_OUTSIDE", SI.get(SI.TELE_KEYBINDING_PRIMARY_RESIDENCE_OUTSIDE))
ZO_CreateStringId("SI_BINDING_NAME_BMU_GUILD_HOUSE", SI.get(SI.TELE_KEYBINDING_GUILD_HOUSE_BMU))
ZO_CreateStringId("SI_BINDING_NAME_BMU_TOGGLE_MAIN_DUNGEON_FINDER", SI.get(SI.TELE_KEYBINDING_TOGGLE_MAIN_DUNGEON_FINDER))
ZO_CreateStringId("SI_BINDING_NAME_BMU_TRACKED_QUEST", SI.get(SI.TELE_KEYBINDING_TRACKED_QUEST))
